export const monitoredDevices = {
  device1: {
    name: "Device 1",
    id: "BOT-AG-102",
    state: "Active",
    sync: "2 min ago",
    distance: "9.8",
    area: "3.6",
    pesticide: "21.3",
    time: "6.2",
    completion: "68",
    battery: 84,
    tank: 72,
    uncovered: "1.7",
    task: "In Progress",
    distanceData: [
      { time: "06:00", distance: 0.4 },
      { time: "07:00", distance: 1.8 },
      { time: "08:00", distance: 3.6 },
      { time: "09:00", distance: 5.1 },
      { time: "10:00", distance: 6.7 },
      { time: "11:00", distance: 8.4 },
      { time: "12:00", distance: 9.8 },
    ],
    pesticideData: [
      { session: "S1", liters: 3.2 },
      { session: "S2", liters: 4.7 },
      { session: "S3", liters: 3.9 },
      { session: "S4", liters: 5.4 },
      { session: "S5", liters: 4.1 },
    ],
    taskStatusData: [
      { name: "Completed", value: 68, color: "hsl(var(--primary))" },
      { name: "In Progress", value: 22, color: "hsl(var(--accent))" },
      { name: "Not Completed", value: 10, color: "hsl(var(--warning))" },
    ],
    report: {
      distance: "24.6 km",
      area: "8.6 ha",
      pesticide: "52.4 L",
      history: [
        { day: "Mon", distance: 2.8, area: 1.1 },
        { day: "Tue", distance: 3.4, area: 1.4 },
        { day: "Wed", distance: 4.2, area: 1.6 },
        { day: "Thu", distance: 3.9, area: 1.5 },
        { day: "Fri", distance: 5.1, area: 1.8 },
        { day: "Sat", distance: 3.2, area: 1.2 },
        { day: "Sun", distance: 2.0, area: 0.8 },
      ],
      usage: [
        { day: "Mon", liters: 6.4 },
        { day: "Tue", liters: 7.2 },
        { day: "Wed", liters: 9.1 },
        { day: "Thu", liters: 8.4 },
        { day: "Fri", liters: 10.6 },
        { day: "Sat", liters: 6.8 },
        { day: "Sun", liters: 3.9 },
      ],
      insights: ["Highest coverage recorded on Friday.", "Pesticide usage remained aligned with field area.", "Weekly completion improved by 8% compared with the previous report."],
    },
  },
  device2: {
    name: "Device 2",
    id: "BOT-AG-118",
    state: "Active",
    sync: "5 min ago",
    distance: "6.4",
    area: "2.1",
    pesticide: "14.8",
    time: "4.5",
    completion: "54",
    battery: 76,
    tank: 58,
    uncovered: "1.8",
    task: "Completed",
    distanceData: [
      { time: "06:00", distance: 0.2 },
      { time: "07:00", distance: 1.1 },
      { time: "08:00", distance: 2.4 },
      { time: "09:00", distance: 3.7 },
      { time: "10:00", distance: 4.9 },
      { time: "11:00", distance: 5.8 },
      { time: "12:00", distance: 6.4 },
    ],
    pesticideData: [
      { session: "S1", liters: 2.6 },
      { session: "S2", liters: 3.1 },
      { session: "S3", liters: 2.8 },
      { session: "S4", liters: 3.4 },
      { session: "S5", liters: 2.9 },
    ],
    taskStatusData: [
      { name: "Completed", value: 54, color: "hsl(var(--primary))" },
      { name: "In Progress", value: 34, color: "hsl(var(--accent))" },
      { name: "Not Completed", value: 12, color: "hsl(var(--warning))" },
    ],
    report: {
      distance: "18.2 km",
      area: "6.4 ha",
      pesticide: "39.8 L",
      history: [
        { day: "Mon", distance: 1.8, area: 0.8 },
        { day: "Tue", distance: 2.4, area: 0.9 },
        { day: "Wed", distance: 3.1, area: 1.1 },
        { day: "Thu", distance: 2.9, area: 1.0 },
        { day: "Fri", distance: 3.8, area: 1.4 },
        { day: "Sat", distance: 2.5, area: 0.9 },
        { day: "Sun", distance: 1.7, area: 0.3 },
      ],
      usage: [
        { day: "Mon", liters: 4.3 },
        { day: "Tue", liters: 5.8 },
        { day: "Wed", liters: 6.9 },
        { day: "Thu", liters: 6.2 },
        { day: "Fri", liters: 8.1 },
        { day: "Sat", liters: 5.4 },
        { day: "Sun", liters: 3.1 },
      ],
      insights: ["Average daily coverage was 0.91 ha.", "Tank usage was consistent across active days.", "Two field sessions remained in progress at report close."],
    },
  },
  device3: {
    name: "Device 3",
    id: "BOT-AG-125",
    state: "Offline",
    sync: "1 hr ago",
    distance: "3.2",
    area: "1.3",
    pesticide: "7.6",
    time: "2.1",
    completion: "41",
    battery: 49,
    tank: 44,
    uncovered: "1.9",
    task: "Completed",
    distanceData: [
      { time: "06:00", distance: 0.3 },
      { time: "07:00", distance: 0.9 },
      { time: "08:00", distance: 1.5 },
      { time: "09:00", distance: 2.4 },
      { time: "10:00", distance: 3.2 },
    ],
    pesticideData: [
      { session: "S1", liters: 1.8 },
      { session: "S2", liters: 2.3 },
      { session: "S3", liters: 1.6 },
      { session: "S4", liters: 1.9 },
    ],
    taskStatusData: [
      { name: "Completed", value: 41, color: "hsl(var(--primary))" },
      { name: "In Progress", value: 0, color: "hsl(var(--accent))" },
      { name: "Not Completed", value: 59, color: "hsl(var(--warning))" },
    ],
    report: {
      distance: "11.8 km",
      area: "4.5 ha",
      pesticide: "25.9 L",
      history: [
        { day: "Mon", distance: 1.4, area: 0.5 },
        { day: "Tue", distance: 1.9, area: 0.8 },
        { day: "Wed", distance: 2.2, area: 0.9 },
        { day: "Thu", distance: 1.7, area: 0.6 },
        { day: "Fri", distance: 2.4, area: 1.0 },
        { day: "Sat", distance: 1.5, area: 0.5 },
        { day: "Sun", distance: 0.7, area: 0.2 },
      ],
      usage: [
        { day: "Mon", liters: 3.2 },
        { day: "Tue", liters: 4.1 },
        { day: "Wed", liters: 4.8 },
        { day: "Thu", liters: 3.6 },
        { day: "Fri", liters: 5.3 },
        { day: "Sat", liters: 3.4 },
        { day: "Sun", liters: 1.5 },
      ],
      insights: ["Offline status reflects the last reported telemetry.", "Coverage was highest before the connection gap.", "Tank level should be checked before the next monitored run."],
    },
  },
  device4: {
    name: "Device 4",
    id: "BOT-AG-131",
    state: "Active",
    sync: "9 min ago",
    distance: "4.7",
    area: "1.8",
    pesticide: "10.9",
    time: "3.4",
    completion: "47",
    battery: 68,
    tank: 62,
    uncovered: "2.0",
    task: "In Progress",
    distanceData: [
      { time: "06:00", distance: 0.1 },
      { time: "07:00", distance: 0.8 },
      { time: "08:00", distance: 1.7 },
      { time: "09:00", distance: 2.6 },
      { time: "10:00", distance: 3.5 },
      { time: "11:00", distance: 4.2 },
      { time: "12:00", distance: 4.7 },
    ],
    pesticideData: [
      { session: "S1", liters: 2.0 },
      { session: "S2", liters: 2.6 },
      { session: "S3", liters: 2.1 },
      { session: "S4", liters: 2.4 },
      { session: "S5", liters: 1.8 },
    ],
    taskStatusData: [
      { name: "Completed", value: 47, color: "hsl(var(--primary))" },
      { name: "In Progress", value: 38, color: "hsl(var(--accent))" },
      { name: "Not Completed", value: 15, color: "hsl(var(--warning))" },
    ],
    report: {
      distance: "15.5 km",
      area: "5.8 ha",
      pesticide: "32.6 L",
      history: [
        { day: "Mon", distance: 1.6, area: 0.6 },
        { day: "Tue", distance: 2.1, area: 0.8 },
        { day: "Wed", distance: 2.7, area: 1.0 },
        { day: "Thu", distance: 2.4, area: 0.9 },
        { day: "Fri", distance: 3.1, area: 1.2 },
        { day: "Sat", distance: 2.2, area: 0.8 },
        { day: "Sun", distance: 1.4, area: 0.5 },
      ],
      usage: [
        { day: "Mon", liters: 3.8 },
        { day: "Tue", liters: 4.6 },
        { day: "Wed", liters: 5.5 },
        { day: "Thu", liters: 5.0 },
        { day: "Fri", liters: 6.4 },
        { day: "Sat", liters: 4.5 },
        { day: "Sun", liters: 2.8 },
      ],
      insights: ["Coverage pattern is stable across active sessions.", "Pesticide usage is proportional to reported area.", "Current task remains in progress based on latest telemetry."],
    },
  },
};

export type DeviceKey = keyof typeof monitoredDevices;
export const monitoredDeviceList = Object.values(monitoredDevices);
